/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Arrays */

#ifndef _Included_Arrays
#define _Included_Arrays
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Arrays
 * Method:    reverse
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Arrays_reverse
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
