/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exceptions */

#ifndef _Included_Exceptions
#define _Included_Exceptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exceptions
 * Method:    CatchThrow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Exceptions_CatchThrow
  (JNIEnv *, jobject);

/*
 * Class:     Exceptions
 * Method:    another
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Exceptions_another
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
