/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CallMethods */

#ifndef _Included_CallMethods
#define _Included_CallMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CallMethods
 * Method:    callOne
 * Signature: (LSomeMethods;)V
 */
JNIEXPORT void JNICALL Java_CallMethods_callOne
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CallMethods
 * Method:    callTwo
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_CallMethods_callTwo
  (JNIEnv *, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
