/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Strings */

#ifndef _Included_Strings
#define _Included_Strings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Strings
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Strings_print
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Strings
 * Method:    give
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Strings_give
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
