/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Objects */

#ifndef _Included_Objects
#define _Included_Objects
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Objects
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Objects_create
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
