/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SetSomeVars */

#ifndef _Included_SetSomeVars
#define _Included_SetSomeVars
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SetSomeVars
 * Method:    modifyx
 * Signature: (LVars;I)V
 */
JNIEXPORT void JNICALL Java_SetSomeVars_modifyx
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     SetSomeVars
 * Method:    modifyy
 * Signature: (LVars;I)V
 */
JNIEXPORT void JNICALL Java_SetSomeVars_modifyy
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
