/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Vars */

#ifndef _Included_Vars
#define _Included_Vars
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Vars
 * Method:    demo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Vars_demo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
