/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CallBack */

#ifndef _Included_CallBack
#define _Included_CallBack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CallBack
 * Method:    callMe
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CallBack_callMe
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
