/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Number */

#ifndef _Included_Number
#define _Included_Number
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Number
 * Method:    welcome
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Number_welcome
  (JNIEnv *, jobject);

/*
 * Class:     Number
 * Method:    factorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Number_factorial
  (JNIEnv *, jobject, jint);

/*
 * Class:     Number
 * Method:    print_string
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Number_print_1string
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
