/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Array */

#ifndef _Included_Array
#define _Included_Array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Array
 * Method:    mkArray
 * Signature: (I)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_Array_mkArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     Array
 * Method:    ret
 * Signature: ([LDomino;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_Array_ret
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
